# =============================================================
#  client.py  -  Bandwidth Measurement Tool (Client Side)
#  What it does:
#    • Connects to the server
#    • Sends large chunks of data (5 MB, 10 MB, 50 MB)
#    • Times each transfer
#    • Calculates and prints bandwidth (MB/s)
#    • Runs each size test multiple times and averages the results
#    • Saves everything to results.txt
# =============================================================

import socket     
import time       



HOST            = "localhost"   
PORT            = 9090          
RUNS_PER_SIZE   = 3             
SIMULATED_DELAY = 0.2           


DATA_SIZES = {
    " 5 MB":  5  * 1024 * 1024,
    "10 MB": 10  * 1024 * 1024,
    "50 MB": 50  * 1024 * 1024,
}



def run_single_test(data: bytes) -> float:
    """
    Connects to the server, sends `data`, measures time, returns MB/s.

    Parameters
    ----------
    data : bytes
        The raw bytes to send (pre-generated by the caller).

    Returns
    -------
    float
        Measured bandwidth in MB/s.
    """

   
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

   
    client_socket.connect((HOST, PORT))

   
    time.sleep(SIMULATED_DELAY)

    
    start_time = time.perf_counter()

   
    client_socket.sendall(data)

   
    client_socket.shutdown(socket.SHUT_WR)

   
    end_time = time.perf_counter()

    
    time_taken  = end_time - start_time                
    data_mb     = len(data) / (1024 * 1024)            
    bandwidth   = data_mb / time_taken                 

    
    client_socket.close()

    return bandwidth, time_taken, data_mb



def main():
    all_results = []   

    print("=" * 55)
    print("         NETWORK BANDWIDTH MEASUREMENT TOOL")
    print("=" * 55)
    print(f"  Connecting to : {HOST}:{PORT}")
    print(f"  Runs per size : {RUNS_PER_SIZE}")
    print(f"  Simulated lag : {SIMULATED_DELAY}s before each send")
    print("=" * 55)

    
    for label, size_bytes in DATA_SIZES.items():

        print(f"\n[TEST] Data size: {label}")
        print("-" * 45)

        
        payload = bytes(size_bytes)

        run_speeds = []   

        
        for run_number in range(1, RUNS_PER_SIZE + 1):
            print(f"  Run {run_number}/{RUNS_PER_SIZE}  ", end="", flush=True)

            speed, duration, mb = run_single_test(payload)
            run_speeds.append(speed)

           
            result_line = (
                f"  Run {run_number}/{RUNS_PER_SIZE} | "
                f"Data: {mb:.1f} MB | "
                f"Time: {duration:.6f}s | "
                f"Speed: {speed:.2f} MB/s"
            )
            print(result_line.strip())
            all_results.append(result_line)

        
        average_speed = sum(run_speeds) / len(run_speeds)

        summary_line = (
            f"\n  >>> Average speed for {label.strip()}: "
            f"{average_speed:.2f} MB/s\n"
        )
        print(summary_line)
        all_results.append(summary_line)

    
    print("\n" + "=" * 55)
    print("          FINAL SUMMARY (last 50 MB run)")
    print("=" * 55)
    
    payload_50 = bytes(50 * 1024 * 1024)
    final_speed, final_time, final_mb = run_single_test(payload_50)
    print(f"\n--- Bandwidth Test Result ---")
    print(f"Data sent  : {final_mb:.1f} MB")
    print(f"Time taken : {final_time:.6f} seconds")
    print(f"Speed      : {final_speed:.2f} MB/s")

    
    with open("results.txt", "w") as f:
        f.write("BANDWIDTH TEST RESULTS\n")
        f.write("=" * 55 + "\n")
        for line in all_results:
            f.write(line + "\n")
        f.write("\n--- Final 50 MB run ---\n")
        f.write(f"Data sent  : {final_mb:.1f} MB\n")
        f.write(f"Time taken : {final_time:.6f} seconds\n")
        f.write(f"Speed      : {final_speed:.2f} MB/s\n")

    print("\n[INFO] Results saved to results.txt")


if __name__ == "__main__":
    main()